# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and Publish download-aet Docker Image

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./tds-examples/python/

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/download-aet
          labels: |
            org.opencontainers.image.title=Download CMRSET AET
            org.opencontainers.image.description=The CMRSET Landsat data products provide accurate, high-resolution (30 m) / high-frequency (monthly) / continuous (no gaps due to cloud) actual evapotranspiration (AET) for Australia using the CMRSET algorithm. This package will download the CMRSET actual evapotranspiration products from the TERN Data Services Catalogue as Cloud-Optimized GeoTIFF's. This package is effectively a bot which will scrape the online data archive for you (to save you clicking on links). Each monthly image (~20 GB) has been divided into 12 smaller tiles (4x3, and less than 4 GB each) in order to make downloading simpler (i.e if your study site fits within one tile you can just download that particular tile). A VRT file (virtual dataset) has also been provided for each month which will mosaic the 12 tiles into a complete image of Australia. https://portal.tern.org.au/actual-evapotranspiration-australia-cmrset-algorithm/21915
            org.opencontainers.image.url=https://portal.tern.org.au/actual-evapotranspiration-australia-cmrset-algorithm/21915
            org.opencontainers.image.documentation=https://github.com/ternaustralia/cmrset-examples/tree/main/tds-examples
            org.opencontainers.image.source=https://github.com/ternaustralia/cmrset-examples/tree/main/tds-examples/python
            org.opencontainers.image.vendor=Terrestrial Ecosystem Research Network (TERN), The Commonwealth Scientific and Industrial Research Organisation (CSIRO)

          flavor: |
            latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          file: tds-examples/python/Dockerfile
          context: ./tds-examples/python/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
