# This is a workflow to trigger an image build of this repository on mybinder.org




name: 'Trigger Binder build'

on:
  push:
    branches: [main]

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1.0.4
        with:
          target-repo: ternaustralia/cmrset-examples
          target-state: main
